### PR TITLE
Alternative input

### PR DESCRIPTION
**Pull request by ferenckata**
## PR checklist

- Adding nextflow script to create sample sheet from fastq folder path. However, I found it is superfluous and thus created an alternative input option to start the whole pipeline from fastq folder path instead.
- Have not added tests yet, other than that it runs on the example data.
- README is updated
- Usage Documentation in `docs/usage.md` is NOT updated YET.

### CODE REVIEW

**Comment by sidorov-si** [comment]
Hi Katalin! Nice start!

Could you please:

1) Remove the module `make_input_csv.nf` and its inclusion in the main workflow if you think we don't need it (but first see below).

2) Implement autodetection of whether reads are single-end or paired-end and remove the `--singleEnd` parameter (the `input_reads.sh` script does the autodetection, and I think it's better that way, because forgetting to add `--singleEnd` is extremely easy). Of course, for that you could return to your `make_input_csv.nf` module or modify the `sh` script.

3) Initialise `params.samplesheet`, so that the user does not get the warning:

```
WARN: Access to undefined parameter `samplesheet` -- Initialise it to a default value eg. `params.samplesheet = some_value`
```

4) Make sure that the module `CAT_FASTQ` actually merges per-lane input FASTQ files when the user sets `--infolder` (currently, it doesn't, although it does when `--samplesheet` is set). The [`.view()`](https://www.nextflow.io/docs/latest/operator.html#view) channel operator is a great help when debugging channel structures (most probably, the problem is somewhere in the structure of the `ch_fastq` channel that you create from the input folder).

5) Add a test dir with per-sample subdirs for PE reads and a test dir with per-sample subdirs for SE reads and test your implementation in these two cases.

We probably will not be using `docs/usage.md` (I think that having all necessary instructions in one README file is more convenient), so no need to update that `md`.

**Comment by ferenckata** [comment]
Sounds good, thanks for the feedback! I will get back to you with the updates

**Comment by ferenckata** [comment]
Hi again,
I think I addressed all the comments. Additionally, I updated an input check (when I forgot to modify the samplesheet it was not caught efficiently). Plus, added a tentative params file (it helped me doing the development, and probably with extra documentation would be useful for others too).
Let me know what you think.

**Comment by sidorov-si** [comment]
Hey Kata, excellent job! 
Sorry for the delay with the review!
The only thing that needs correction now is that sample names are different when using a sample sheet (these names are correct) and when using an input folder (these names contain an additional piece of a file name that needs to be removed). For example, when running the pipeline on single-end reads from the sample sheet, we get sample names "S1" and "S2" (that's how it should be), but when we run on the same reads from the input dir, we get "S1_S1" and "S2_S2". A similar thing happens with paired-end reads.

**Comment by ferenckata** [comment]
Hei,

It is fixed now.

I answered in the email, but now I remembered that actually when you run from the samplesheet, the value of the first column is picked up whatever that is. It is apparently not part of the samplesheet check or the channel creation to ensure the name is really only the samplename (that is where I was confused first, in line 85 of customcage.nf it looked like cutting the sample name by underscore so I just took that line).

See the example below (with the original line: `meta.id = meta.id.split('_')[0..-2].join('_')` ):

samplesheet:
```
sample,fastq_1,fastq_2,single_end
S2_S2_L001_R1_001,/home/katalitf/Documents/customcageq/assets/sacCer_fastq/se/S2_S2_L001_R1_001.fastq.gz,,True
S1,/home/katalitf/Documents/customcageq/assets/sacCer_fastq/se/S1_S1_L001_R1_001.fastq.gz,,True
S1_S1_L002,/home/katalitf/Documents/customcageq/assets/sacCer_fastq/se/S1_S1_L002_R1_001.fastq.gz,,True
S2_S2,/home/katalitf/Documents/customcageq/assets/sacCer_fastq/se/S2_S2_L002_R1_001.fastq.gz,,True
```

```
[[id:S2_S2_L001_R1_001, single_end:true], [/home/katalitf/Documents/customcageq/assets/sacCer_fastq/se/S2_S2_L001_R1_001.fastq.gz]]
[[id:S1, single_end:true], [/home/katalitf/Documents/customcageq/assets/sacCer_fastq/se/S1_S1_L001_R1_001.fastq.gz]]
[[id:S1_S1_L002, single_end:true], [/home/katalitf/Documents/customcageq/assets/sacCer_fastq/se/S1_S1_L002_R1_001.fastq.gz]]
[[id:S2_S2, single_end:true], [/home/katalitf/Documents/customcageq/assets/sacCer_fastq/se/S2_S2_L002_R1_001.fastq.gz]]
```

To overwrite the input sample names (and thus fix the example below) you need to have `meta.id = meta.id.split('_')[0]` in line 85, but then you cannot have underscore in the input sample name.

**Comment by sidorov-si** [comment]
Good catch! Please see my reply in our email thread about the PR.

**Comment by sidorov-si** [comment]
Hi Kata,

Thank you very much for setting up the actions.

With this PR, we're almost there! I tested it more and would like you to fix the following:

1) When using a sample sheet with a non-existent R1 file, the pipeline stops but does not print the error message that you provided in the create_fastq_channel function. Could you possibly look into that? I haven't checked a non-existent R2 file, but most probably there will be the same problem.

2) Could you please initialise params.samplesheet at the beginning of the customcage.nf workflow (just in front of all other param initialisations), so that the user does not get a warning when providing --infolder?

**Comment by ferenckata** [comment]
Hi Slava,

thanks for checking this, good catch. Apparently, if you use exit 1 it prints in the log but not on the stdout. A bit weird, because I think I saw it working before.

**Comment by sidorov-si** [comment]
Wonderful job, Katalin!
After a bit of additional testing (all good!) and refreshing README, I'm merging the PR!

**Pull request merged**
